// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrZgshE4ga5RW293sghYTX1Dg0qS3Tqi8',
    appId: '1:646748692869:web:9e53216da1106d32a7e4ec',
    messagingSenderId: '646748692869',
    projectId: 'pantry-g15p01',
    authDomain: 'pantry-g15p01.firebaseapp.com',
    storageBucket: 'pantry-g15p01.firebasestorage.app',
    measurementId: 'G-Z4XG1ZGGBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxNI2JRVcKpVBIrIcUyB1-JUtJw6OA6M',
    appId: '1:646748692869:android:93303cc3e4188b03a7e4ec',
    messagingSenderId: '646748692869',
    projectId: 'pantry-g15p01',
    storageBucket: 'pantry-g15p01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFEOd-mT1RqAlv5atXbtw-2ONa-2ok_wg',
    appId: '1:646748692869:ios:838873375a776c19a7e4ec',
    messagingSenderId: '646748692869',
    projectId: 'pantry-g15p01',
    storageBucket: 'pantry-g15p01.firebasestorage.app',
    iosClientId: '646748692869-dcubcenl2dgarcfb16a412sld38fmkut.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFEOd-mT1RqAlv5atXbtw-2ONa-2ok_wg',
    appId: '1:646748692869:ios:838873375a776c19a7e4ec',
    messagingSenderId: '646748692869',
    projectId: 'pantry-g15p01',
    storageBucket: 'pantry-g15p01.firebasestorage.app',
    iosClientId: '646748692869-dcubcenl2dgarcfb16a412sld38fmkut.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrZgshE4ga5RW293sghYTX1Dg0qS3Tqi8',
    appId: '1:646748692869:web:8e89a87a33f07194a7e4ec',
    messagingSenderId: '646748692869',
    projectId: 'pantry-g15p01',
    authDomain: 'pantry-g15p01.firebaseapp.com',
    storageBucket: 'pantry-g15p01.firebasestorage.app',
    measurementId: 'G-6GND9LPYV1',
  );
}
